server:
  port: 8302
spring:
  application:
    name: student-service
  data:
    mongodb:
      database: test
      uri: mongodb://localhost:27017/test

      keycloak:
        auth-server-url: http://localhost:8080/auth
        principal-attribute: preferred_username
        public-client: true
        realm: spring-boot
        resource: student-service
        security-constraints:
          - authRoles:
              - user
            securityCollections:
              - patterns:
                  - /student/*
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    hostname: localhost
